### ISSUE TITLE
Change the repo name

### ISSUE THREAD

**Issue by Pixailz** [Pixailz/ft_transcendence#10]
we have to change the repo name as every student that search `ft_transcendence` will find our repo,

a name like Pongo will help to 'hide' the repo ;)

**Comment by clinche** [comment]
Let them find us and get a bad grade cause we're too good for them

**Comment by RuBeeN-cmd** [comment]
I don't have an opinion on the question, both solutions suit me

**Comment by Pixailz** [comment]
> Let them find us and get a bad grade cause we're too good for them
> 
> Or we hide some pings to a server and dos everytime we get a connection, or we hide some pings AND a backdoor

You are right, let's be so brilliant that they can't copy this repo xD
