### ISSUE TITLE
Implement AuthGuards

### ISSUE THREAD

**Issue by clinche** [Pixailz/ft_transcendence#11]
## What are AuthGuards

AuthGuards are decorators that, when put in front of a backend route, will validate the users and authorize or deny the route execution
Full documentation [here](https://docs.nestjs.com/guards).

## How Could it be Done
Follow the docs to implement a basic AuthGuard with JWT. This guard will only be responsible to tell if a user have our signed JWT **and** is rightly authenticated.

Then, we will have to implement more Guards, notably RoleGuards, to quickly know if a user can access a chatroom, modify its title, etc.

If you see use cases, difficulties or think it shouldnt be used like that, please comment

Beginning of development is expected to begin after #9 is resolved and [backend-dbmodule](https://github.com/Pixailz/ft_transcendence/tree/backend-dbmodule) is merged, thus we shouldn't create a branch now

**Comment by Pixailz** [comment]
> Full documentation [here](https://docs.nestjs.com/guards).

you know sometimes the documention ...

**Comment by clinche** [comment]
Anticipated timeline of work will not be possible in real life. As pointed by #18, we need to redo almost every authentication code, and we will implement authguards at the same time
