### ISSUE TITLE
Create relation in database

### ISSUE THREAD

**Issue by Ycaro02** [Pixailz/ft_transcendence#15]
Explain feature
Create a basic relation table for User, chat and game

Folder/File impacted
src/nestjs/src/modules/database

Author:  Ycaro02

**Comment by Ycaro02** [comment]
J' ai récuperer la derniere version depuis main bien sûr, une idée de nom pour cette magnifique branch ?

**Comment by Pixailz** [comment]
Hmm **relation-database** je pense

Le nom des branch est pas important en sois :p

D'ailleurs je vais regarder aussi, hier je regardais sur dbdiagram pour faire le skelet de la DB :)

**Comment by Pixailz** [comment]
Sinon nickel dans la branch backend-dbmodule :)
