### ISSUE TITLE
[META] [Back&Front] Redo all the authentications

### ISSUE THREAD

**Issue by clinche** [Pixailz/ft_transcendence#18]
## Oopsie
In the current state, authentications are not working right and are following zero good practices

## Why??
Few things to set: 
- we cannot make requests on the server side from angular, so all back-end requests need to be done by the client (apologies for when i told otherwise)
- we **could** make requests from the server side but we would need to rewrite everything
- nonetheless, we need to rewrite all authentication logic as we were actually missing a few things:
  - jwt should not be handled by hand in nestjs, and instead should make use of a passport strategy
  - angular should intercept all backend requests, append the token in the authorization header, and make the client do the request (it is still a bad idea to simply expose nestjs)
  - routes in angular should be protected by an authguard but all the actual logic to know if a user is currently logged in should be handled by the backend
  - ***all the angular code will be viewed by the client, all requests will be made by the client, so nothing sensible should be in here***

## How to proceed
- Close issues #7, #8 and #11 as we should stop now worsening the code
- Tidy the code, keep the working parts and remove all parts touching the authentication
- Create new issues for authentication : one issue (and branch) **only** for implementing authguard and jwtpassport in nestjs, then create another issue **only** for implementing authguard in angular

This issue is a meta issue whose purpose is to provide a centralized view of where we are concerning authentication

**Comment by clinche** [comment]
Created #22 to implement backend authentication

**Comment by Pixailz** [comment]
i don't like the fact that we have to use passport, as well as i don't use passport-42 for the token, i don't know why we would have to use it for jwt :/

**Comment by clinche** [comment]
as i get it by reading docs, we code authentication with 42 in nestjs, and we use passport to "automate" protecting endpoints to keep non logged user from accessing it

> At a high level, Passport executes a series of steps to:
> Authenticate a user by verifying their "credentials" (such as username/password, JSON Web Token (JWT), or identity token from an Identity Provider)
> Manage authenticated state (by issuing a portable token, such as a JWT, or creating an Express session)
> Attach information about the authenticated user to the Request object for further use in route handlers
[source](https://docs.nestjs.com/recipes/passport)

**Comment by Pixailz** [comment]
## New login system

as mentioned in #31 which is closed, the authentification process is now done, the new login process is as follow:

1. clicking on the upper right login button 
1. redirection to the login page
1. click on the 42 login button
1. then accept to share info on the 42 api side.
1. the 42 api redirect us with value in the query `code`, on this url `https://localhost/login` 
1. we intercept that code in the front end, and pass it to the back
1. in the back we call the 42 api with all the necessary key + the mentioned above code to retrieve all the information about the user (ft_id or ft_login)
1. we then sign the id of the user with JWT and return it back to the front
1. return it to the front, wich will be stored in the local storage, with the key `access_token`

## Guard

there also some guard that have been implemented, in both front and back end, this is a way to check whether an user have access to a certain route, given on condition.

### Back

in the back end there's a `@Public` decorator that allow anyone to access a route, which let the other route private for anyone who's not logged in.

### Front

on the front end, the routing module allow us to use a [function](https://github.com/Pixailz/ft_transcendence/blob/main/src/angularjs/src/app/auth-guard.service.ts) as a check for the route, and work as follow:

1. check for `access_token` in the localstorage
    - if true:  so we check on the back end to verify that token
    - if false: redirect to the /home page ()

1. the backend return `200` on success and `401` on failure
