### ISSUE TITLE
Weird situation, deprecated guard method

### ISSUE THREAD

**Issue by Pixailz** [Pixailz/ft_transcendence#40]
The recent pull request #39, introduce us in weird situation. let me explain

as mentionned in this [comment](https://github.com/Pixailz/ft_transcendence/issues/31#issuecomment-1654611518), the older method use a class, but this way is deprecated. so the new way is to use only a function. this introduce a problem when we have to redirect the user when it don't have the token set, because i have try the `inject(Router)` method but the `inject()` is not in a good context (see [NG0203](https://angular.io/errors/NG0203)). i have also tried to set the `windows.location.href` to login but this cause a weird looping bug on the login page

btw i should mention that there is currently a discussion in an [open issue](https://github.com/angular/angular/issues/50234) talking about this problem

i gave up yesterday but this should be fix i think, a way or another

**Comment by clinche** [comment]
given how they are shouting js code at each other i think it would be better to do it in class as it should be un-deprecated soon and has been the way of doing this since the beginning of angular apparently
