### ISSUE TITLE
Reorganize backend route

### ISSUE THREAD

**Issue by Pixailz** [Pixailz/ft_transcendence#48]
### Explain feature
reorder route on backend, for exemple all route from database should be `/db/user`, `/db/user_chat_room` and so on
+ add a route for getting user info given a token, organised in a userService class

### Folder/File impacted
./src/nestjs/src/modules

**Comment by clinche** [comment]
i approve the need of renaming things but i doubt a /db prefix is the ideal way bc in the end, every request will be processed by checking the db
why not things like /user/profile, /user/chatrooms for getting or setting infos relating to a user, /chatroom for infos or actions about chatrooms, etc ?

**Comment by Pixailz** [comment]
i agreed, i was thinking about a backend route `/user/me` for getting the user info, should i create a userService class that use both `authModule` and `dbUserService` (renamed from userService to dbUserService to avoid confusion) to 'join' those two features ? 

the route for the backend is temporary and like in the case of `/user/me` adjusted to our need
