### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by Pixailz** [Pixailz/ft_transcendence#7]
### Explain feature

register an user after the first login, a simple page that ask for every details we have to

### Folder/File impacted
[./src/angular](https://github.com/Pixailz/ft_transcendence/tree/main/src/angularjs)

Author:

**Comment by Pixailz** [comment]
i don't see it before but the [frontend-userprofil](https://github.com/Pixailz/ft_transcendence/tree/frontend-userprofil), is basically this features

**Comment by clinche** [comment]
Yep, will do it in another branch after this one, at the same time than #8

**Comment by clinche** [comment]
Closed as needed by #18, it will be implemented when AuthGuards are
