### ISSUE TITLE
implement swagger

### ISSUE THREAD

**Issue by clinche** [Pixailz/ft_transcendence#71]
### Explain feature
add swagger and base config

### Folder/File impacted
src/angular/assets/css
src/nestjs

**Comment by Pixailz** [comment]
hmm, i tried the dark mode but it's like that 
![image](https://github.com/Pixailz/ft_transcendence/assets/35565530/9f1eca31-3849-438f-9746-2ad0a214b7bc)

is it normal ? (r.i.p dark mode)

**Comment by Pixailz** [comment]
I'm in the 'péniche' I do the review when I come back ;)

**Comment by clinche** [comment]
no problem but remember to do a `./setup re` to ensure all modifications are set, bc [this](https://github.com/Pixailz/ft_transcendence/assets/101885891/3870ce51-5221-45ef-87cd-fa6b8c117e1f) is what i have on clean git clone

**Comment by RuBeeN-cmd** [comment]
Same thing after ./setup re dev
![image](https://github.com/Pixailz/ft_transcendence/assets/63564987/e41bdb15-dea2-440e-9b16-5c25acf059e6)

**Comment by RuBeeN-cmd** [comment]
> Same thing after ./setup re dev ![image](https://user-images.githubusercontent.com/63564987/261331804-e41bdb15-dea2-440e-9b16-5c25acf059e6.png)

Fixed after setting firefox theme to dark
![image](https://github.com/Pixailz/ft_transcendence/assets/63564987/78d0a6a6-8fca-4f13-a433-05b31bde0493)
