### ISSUE TITLE
A2F

### ISSUE THREAD

**Issue by Unam3dd** [Pixailz/ft_transcendence#87]
### Explain feature
implement A2F double authenticator like google authenticator 

### Folder/File impacted
Authentication files angularjs & nextjs

Author: Unam3dd

**Comment by clinche** [comment]
began implementing twofa logic for backend and frontend:
- added `/auth/2fa` controller to backend handle code verification
  - takes two parameters, nonce and code
    - nonce is a random value assigned to the user while performing 42 code verification
    - code is the twofa code
  - the nonce is currently verified
- added `/2fa` controller to frontend to permit supply of 2fa code
  - after clicking login, if user has enabled twofa, is redirected to it with the nonce
  - no access_token is supplied so if user tries to go to any page he'll be redirected to login
  - `returnUrl` is successfully handled

TODO:
- enable twofa via profile page (currently need to do a PUT to `/profile/me`)
  - it will be needed to modify user in db to add twofa secret and
  - modify frontend to show QR code and do a test before enabling definitely 2fa
- implement a way to verify the supplied twofa code with the secret

**Comment by Pixailz** [comment]
The 2fa will be compatible with any application ? @Unam3dd
